name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.11'
            crypto: true
          - python-version: '3.11'
            crypto: false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: matrix.crypto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install pytest only (openssl fallback)
        if: matrix.crypto == false
        run: |
          python -m pip install --upgrade pip
          pip install pytest>=7.0

      - name: Compile sources
        run: python -m compileall .

      - name: Run tests
        run: pytest -q
